HTML-753 Encounter DateTime error messages are not being translated
openmrs/openmrs-module-htmlformentryui pull request #38
Opened 2020-10-08 07:43 UTC by JFigueiredo89

Issue: https://issues.openmrs.org/browse/HTML-753

2020-10-08 08:09 UTC, mks-d requested changes

2020-10-08 08:09 UTC, mks-d commented on omod/src/main/java/org/openmrs/module/htmlformentryui/fragment/controller/htmlform/EnterHtmlFormFragmentController.java
> +                validationErrors.add(new FormSubmissionError("general-form-error",  Context.getMessageSourceService().getMessage("htmlformentryui.datetimeAfterVisitDate")));
Rather do:
```java
validationErrors.add(new FormSubmissionError("general-form-error",  ui.message("htmlformentryui.datetimeAfterVisitDate")));
```

2020-10-08 08:52 UTC, mks-d approved these changes
LGTM, @mogoodrich?

2020-10-08 13:13 UTC, mogoodrich approved these changes
LGTM, thanks!  Just to confirm, were the translations added to Transifex?

2020-10-20 08:55 UTC, mks-d approved these changes
@mogoodrich we will figure out @JFigueiredo89's Transifex access later (as I couldn't even figure out what was happening with mine.)

2020-10-20 08:55 UTC, merged

2020-10-20 13:26 UTC, mogoodrich commented
That's fine @mks-d but realize until you get them in Transifex, the next time anyone pulls in translations from Transifex the French and Spanish translations will be overridden with the English text.

Feel free to ping me on Slack with your Transifex username and I can look into making sure you have access.